blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('ticket', views.ticket, name="ticket"),
    path('list_information', views.list_information),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/new_post', views.new_post, name="new_post"),
    path('profile/edit_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),


]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_jalali.db import models as jmodels
from django.urls import reverse
from django_resized import ResizedImageField
from django.template.defaultfilters import slugify


# Manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        REJECTED = 'RJ', 'Rejected'

    # relations
    auther = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_posts")
    # data fields
    title = models.CharField(max_length=250)
    description = models.TextField()
    slug = models.SlugField(max_length=250)  # from urls
    # data
    publish = jmodels.jDateTimeField(default=timezone.now)  # from date
    created = jmodels.jDateTimeField(auto_now_add=True)  # date now
    update = jmodels.jDateTimeField(auto_now=True)  # change date if edit post
    # choice fields
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    reading_time = models.PositiveIntegerField(verbose_name="زمان مطالعه")

    # objects = models.Manager
    objects = jmodels.jManager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])

    def save(self, *arg, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(). save(*arg, *kwargs)

    def delete(self, *arg, **kwargs):
        for img in self.images.all():
            storage, path = img.image_file.storage, img.image_file.path
            storage.delete(path)
        super().delete(*arg, *kwargs)


class Ticket(models.Model):
    message = models.TextField(verbose_name="پیام")
    name = models.CharField(max_length=250, verbose_name="نام")
    email = models.EmailField(verbose_name="ایمیل")
    phone = models.CharField(max_length=11, verbose_name="شماره تماس")
    subject = models.CharField(max_length=250, verbose_name="موضوع")

    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"

    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name="پست")
    name = models.CharField(max_length=250, verbose_name="نام")
    body = models.TextField(verbose_name="متن کامنت")
    created = jmodels.jDateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")  # date now
    update = jmodels.jDateTimeField(auto_now=True, verbose_name="تاریخ ویرایش")  # change date if edit post
    active = models.BooleanField(default=False, verbose_name="وضعیت")

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"

    def __str__(self):
        return f"{self.name}: {self.post}"


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images", verbose_name="تصویر")
    image_file = ResizedImageField(upload_to="post_images/", size=[500, 500], quality=75, crop=['middle', 'center'])
    title = models.CharField(max_length=250, verbose_name="عنوان", null=True, blank=True)
    description = models.TextField(verbose_name= "توضیحات", null=True, blank=True)
    created = jmodels.jDateTimeField(auto_now_add=True)  # date now

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "تصویر"
        verbose_name_plural = "تصویر ها"

    def delete(self, *arg, **kwargs):
        storage, path = self.image_file.storage, self.image_file.path
        storage.delete(path)
        super().delete(*arg, *kwargs)

    def __str__(self):
        return self.title if self.title else "None"

blog/forms.py
from django import forms
from .models import Comment, Post


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن را عددی وارد کنید!")
            else:
                return phone


class CommentForm(forms.ModelForm):

    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است!")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول")
    image2 = forms.ImageField(label="تصویر دوم")

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from rest_framework.decorators import api_view
from rest_framework.response import Response
import json
from django.core import serializers
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity


# Create your views here.


def index(request):
    return render(request, "blog/index.html")


# def post_list(request):
#     posts = Post.published.all()
#     paginator = Paginator(posts, 3)
#     page_number = request.GET.get('page', 1)
#     try:
#         posts = paginator.page(page_number)
#     except EmptyPage:
#         posts = paginator.page(paginator.num_pages)
#     except PageNotAnInteger:
#         posts = paginator.page(1)
#     context = {
#         'posts': posts,
#     }
#     return render(request, "blog/list.html", context)

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/list.html"


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, "blog/detail.html", context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/detail.html"


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'],
                                  phone=cd['phone'], subject=cd['subject'])
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, "forms/comment.html", context)


@api_view(["GET"])
def list_information(request):
    posts = Post.published.all()
    post_data = serializers.serialize('json', posts)
    post_data_json = json.loads(post_data)
    context = {
        'post': post_data_json
    }
    return Response(context)


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query))\
                .filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query))\
                .filter(similarity__gt=0.1)
            results = (results1 | results2).order_by('-similarity')
    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)


def profile(request):
    user = request.user
    posts = Post.published.filter(auther=user)
    return render(request, 'blog/profile.html', {'posts': posts})


def new_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.auther = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/new-post.html', {'form': form})


def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    else:
        return render(request, 'forms/delete-post.html', {'post': post})


def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.auther = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    return render(request, 'forms/new-post.html', {'form': form, 'post': post})

blog/templates/forms/comment.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% block title %}post comment{% endblock %}

{% block content %}

    {% if comment %}
        کامنت شما ثبت شد
        <a href="{{ post.get_absolute_url }}">بازگشت به پست</a>
    {% else %}
    <form method="post" action="{% url 'blog:post_comment' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="افزودن کامنت">
    </form>
    {% endif %}

{% endblock %}

blog/templates/forms/delete-post.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% block title %}post delete{% endblock %}

{% block content %}
    <h2>آیا از حذف پست {{ post.title }} اطمینان دارید؟</h2>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="حذف">
    </form>
    <a href="{% url 'blog:profile' %}">بازگشت به صفحه قبل</a>
{% endblock %}

blog/templates/forms/new-post.html
{% extends 'parent/base.html' %}
{% block title %}profile{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if post %}
        {% for img in post.images.all %}
            <img width="350px" height="200px" src="{{ img.image_file.url }}" alt="{{ img.title }}">
            <a href="{% url 'blog:delete_image' img.id %}">حذف تصویر</a>
        {% endfor %}
    {% endif %}
<br>
<br>
    <input type="submit" value="ثبت">
</form>
{% if form.errors %}
        لطفا خطاهای زیر رااصلاح کنید!
        <br>
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        {{ form.non_field_errors     }}
    {% endif %}

{% endblock %}

blog/templates/forms/ticket.html
{% extends 'parent/base.html' %}
{% block title %}Ticket Form{% endblock %}
{% block content %}

    <form method="post">
    {% csrf_token %}
        نام و نام خانوادگی:
    <input type="text" name="name" required
            {% if form.name.value %} value="{{ form.name.value }}" {% endif %}>
        <br>
        ایمیل:
    <input type="email" name="email"
            {% if form.email.value %} value="{{ form.email.value }}" {% endif %}>
        <br>
        شماره تماس:
    <input type="text" name="phone" required maxlength="11"
            {% if form.phone.value %} value="{{ form.phone.value }}" {% endif %}>
        <br>
        متن:
    <textarea name="message">
        {% if form.message.value %} {{ form.message.value }} {% endif %}</textarea>
        <br>

    <select name="subject">
        <option value="پیشنهاد"
                {% if form.subject.value == 'پیشنهاد' %} selected {% endif %}>
            پیشنهادات</option>
        <option value="انتقاد"
                {% if form.subject.value == 'انتقاد' %} selected {% endif %}>
            انتقادات</option>
        <option value="گزارش"
                {% if form.subject.value == 'گزارش' %} selected {% endif %}>
            گزارش</option>
    </select>
        <br>
    <input type="submit" , value="ثبت تیکت">
    </form>
    {% if form.errors %}
        لطفا خطاهای زیر رااصلاح کنید!
        <br>
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        {{ form.non_field_errors     }}
    {% endif %}
{% endblock %}